# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directories:
      - "/AntPlus"
      - "/AntRadioInterface"
      - "/AntPlus.Extensions.Hosting"
      - "/Examples/AntUsbStick"
      - "/AntPlus.UnitTests"
      - "/Extensions/Hosting/Hosting.UnitTests"
      - "/Examples/WpfUsbStickApp"
      - "/Examples/MAUI-gRPC/AntGrpcShared"
      - "/Examples/MAUI-gRPC/AntGrpcService"
      - "/Examples/MAUI-gRPC/MauiAntGrpcClient"
    schedule:
      interval: "weekly"
    groups:
      nuget:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
