# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ANT+ .NET Test

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    permissions:
      # required for all workflows
      security-events: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: |
        dotnet restore AntPlus
        dotnet restore AntRadioInterface
        dotnet restore AntPlus.Extensions.Hosting
        dotnet restore AntPlus.UnitTests
        dotnet restore Examples/AntUsbStick
        dotnet restore Extensions/Hosting/Hosting.UnitTests
        dotnet restore Documentation/Documentation.shfbproj
    - name: Build
      run: dotnet build --no-restore --configuration Github  -p:GeneratePackageOnBuild=false
    - name: Test
      run: dotnet test --no-build --verbosity minimal --configuration Github
    - name: Build Documentation
      run: dotnet build Documentation/Documentation.shfbproj --no-restore --configuration Release
      
