# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths:
      - "AntPlus/**"
      - "AntRadioInterface/*"
      - "Examples/AntUsbStick/*"
      - "AntPlus.Extensions.Hosting/*"
    branches: [ "master" ]
  pull_request:
    paths:
      - "AntPlus/**"
      - "AntRadioInterface/*"
      - "Examples/AntUsbStick/*"
      - "AntPlus.Extensions.Hosting/*"
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
# Skip restoring dependencies as we are using the new SDK-style project format
#    - name: Restore dependencies
#      run: dotnet restore ${{ matrix.project }}
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity minimal --configuration Release
