# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_docs:
    runs-on: windows-latest

    env:
      Solution_Name: AntPlus.sln
      Documentation_Project: Documentation\Documentation.shfbproj
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
        
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Install SHFB and framework packages
        run: |
          dir
          dotnet add $env.Documentation_Project package EWSoftware.SHFB --version 2024.12.21
          dotnet add $env.Documentation_Project package EWSoftware.SHFB.NET --version 9.0.0
          
      - name: Build project
        run: msbuild $env:Solution_Name /r /t:Compile /p:Configuration=Release
